
SRC = main.c debug_simple.c ./../../_libs/memmgr.c ./../../_libs/file_io.c ./../../_libs/newlib_stubs.c
LINKEDLIBS = -lm
CFLAGS += -u _printf_float -Wno-implicit-int -Wno-old-style-definition -Wno-return-type

include ../Makefile_nostart
