/* ****************************************************************************
 * AxE SoC Memory Layout Definitions (Auto-generated)
 * 
 * This file is automatically generated from memory_layout.yaml
 * DO NOT EDIT MANUALLY - Changes will be overwritten
 * 
***************************************************************************** */

#ifndef AXE_MEMORY_LAYOUT_H
#define AXE_MEMORY_LAYOUT_H

#include <stdint.h>

/* Virtual Memory Layout */
#define PROGRAM_BASE_ADDR     0x00000000UL
#define PROGRAM_SIZE          0x00010000UL
#define PROGRAM_END_ADDR      0x00010000UL

#define DATA_BASE_ADDR        0x00010000UL
#define DATA_SIZE             0x00008000UL
#define DATA_END_ADDR         0x00018000UL

#define FILE_IO_BASE_ADDR     0x00020000UL
#define FILE_IO_SIZE          0x00040000UL
#define FILE_IO_END_ADDR      0x00060000UL
#define FILE_IO_MAX_FILES     64
#define FILE_IO_BUFFER_SIZE   0x00001000UL

#define MMIO_BASE_ADDR        0x00100000UL
#define MMIO_SIZE             0x00100000UL
#define MMIO_END_ADDR         0x00200000UL

#define FILE_TRIGGERS_BASE    0x00100000UL
#define FILE_OPEN_TRIGGER     (FILE_TRIGGERS_BASE + 0x00)
#define FILE_READ_TRIGGER     (FILE_TRIGGERS_BASE + 0x04)
#define FILE_WRITE_TRIGGER    (FILE_TRIGGERS_BASE + 0x08)
#define FILE_CLOSE_TRIGGER    (FILE_TRIGGERS_BASE + 0x0C)
#define FILE_SIZE_TRIGGER     (FILE_TRIGGERS_BASE + 0x10)

#define FINISH_SIGNAL_ADDR    0x001FFFFCUL

#define STACK_BASE_ADDR       0x00F00000UL
#define STACK_SIZE            0x00100000UL
#define STACK_TOP_ADDR        STACK_BASE_ADDR
#define STACK_BOTTOM_ADDR     (STACK_BASE_ADDR + STACK_SIZE)

#define PHYSICAL_MEMORY_SIZE  0x01000000UL
#define AXI_OFFSET_STEP       0x01000000UL

#endif /* AXE_MEMORY_LAYOUT_H */
